exec(open("src/data.py").read())
exec(open("src/train_unet.py").read())
exec(open("src/train_resnet.py").read())
exec(open("src/train_unet2.py").read())
exec(open("src/train_unet3_conv.py").read())
exec(open("src/train_fractal_unet.py").read())
exec(open("src/train_segnet.py").read())
